# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: njoroge0330@gmail.com
author_name: Maurice Njoroge
has_binder: true
has_settings: false
kind: frontend
labextension_name: fetchextension
project_short_description: A JupyterLab extension.
python_name: fetchextension
repository: https://github.com/NjorogeMaurice/dkan_fetch_datasets_jupyterlab_extension
test: true

